// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StafflyApp.Data;

#nullable disable

namespace StafflyApp.Migrations
{
    [DbContext(typeof(StafflyDbContext))]
    [Migration("20260331130024_UpdateEmployeeNames")]
    partial class UpdateEmployeeNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StafflyApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "TP.HCM",
                            DepartmentID = 1,
                            Email = "kieuvy611@staffly.com",
                            FullName = "Lê Nguyễn Kiều Vy",
                            Phone = "0901234567",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "Hà Nội",
                            DepartmentID = 1,
                            Email = "tvy1611@staffly.com",
                            FullName = "Nguyễn Phạm Thúy Vy",
                            Phone = "0901112223",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "Đà Nẵng",
                            DepartmentID = 2,
                            Email = "qthink1006@staffly.com",
                            FullName = "Nguyễn Huỳnh Quốc Thịnh",
                            Phone = "0903334445",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "Cần Thơ",
                            DepartmentID = 2,
                            Email = "thaouyen@staffly.com",
                            FullName = "Hoàng Thị Thảo Uyên",
                            Phone = "0905556667",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Address = "TP.HCM",
                            DepartmentID = 3,
                            Email = "taha0302@staffly.com",
                            FullName = "Lý Thái Hòa",
                            Phone = "0907778889",
                            Status = "Inactive"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Address = "Bình Dương",
                            DepartmentID = 1,
                            Email = "bvi0610@staffly.com",
                            FullName = "Võ Thị Bảo Vy",
                            Phone = "0909990001",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Address = "Đồng Nai",
                            DepartmentID = 2,
                            Email = "vminhtien@staffly.com",
                            FullName = "Vương Minh Tiến",
                            Phone = "0911223344",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Address = "Long An",
                            DepartmentID = 4,
                            Email = "diva@staffly.com",
                            FullName = "Lady Gaga",
                            Phone = "0912233445",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 9,
                            Address = "Vũng Tàu",
                            DepartmentID = 3,
                            Email = "jack@staffly.com",
                            FullName = "Leonardo Dicaprio",
                            Phone = "0913344556",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 10,
                            Address = "Tiền Giang",
                            DepartmentID = 5,
                            Email = "katty@staffly.com",
                            FullName = "Katty Perry",
                            Phone = "0914455667",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 11,
                            Address = "Kiên Giang",
                            DepartmentID = 1,
                            Email = "thv@staffly.com",
                            FullName = "Kim TaeHyung",
                            Phone = "0915566778",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 12,
                            Address = "An Giang",
                            DepartmentID = 1,
                            Email = "jk97@staffly.com",
                            FullName = "Jeon JungKook",
                            Phone = "0916677889",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 13,
                            Address = "TP.HCM",
                            DepartmentID = 2,
                            Email = "yoonjunggo@staffly.com",
                            FullName = "Go Yoon Jung",
                            Phone = "0917788990",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 14,
                            Address = "Bến Tre",
                            DepartmentID = 1,
                            Email = "xgh@staffly.com",
                            FullName = "Xu Guang Han",
                            Phone = "0918899001",
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeID = 15,
                            Address = "TP.HCM",
                            DepartmentID = 4,
                            Email = "zrn@staffly.com",
                            FullName = "Zhang Ruo Nan",
                            Phone = "0919900112",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("StafflyApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            EmployeeID = 1,
                            IsActive = true,
                            Password = "123",
                            RoleID = 1,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
